-- 分类表
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100),
    icon VARCHAR(255),
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 线路表
CREATE TABLE IF NOT EXISTS routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    name_en VARCHAR(200),
    summary VARCHAR(500),
    description TEXT,
    cover_image VARCHAR(500),
    images TEXT,
    category_id BIGINT,
    difficulty VARCHAR(20) DEFAULT 'medium',
    duration INT,
    distance DECIMAL(10,2),
    price DECIMAL(10,2),
    max_participants INT DEFAULT 20,
    status INT DEFAULT 1,
    featured BOOLEAN DEFAULT FALSE,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20),
    password VARCHAR(255),
    nickname VARCHAR(100),
    avatar VARCHAR(500),
    wechat_openid VARCHAR(100),
    wechat_unionid VARCHAR(100),
    member_level VARCHAR(20) DEFAULT 'bronze',
    points INT DEFAULT 0,
    status INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0
);

-- ============================================
-- CMS 管理员表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    full_name VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cms_admin_users_username ON cms_admin_users(username);
CREATE INDEX IF NOT EXISTS idx_cms_admin_users_role ON cms_admin_users(role);
CREATE INDEX IF NOT EXISTS idx_cms_admin_users_email ON cms_admin_users(email);

-- ============================================
-- CMS 页面表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) UNIQUE NOT NULL,
    name_zh VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cms_pages_slug ON cms_pages(slug);
CREATE INDEX IF NOT EXISTS idx_cms_pages_active ON cms_pages(is_active);

-- ============================================
-- CMS 内容项表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id BIGINT,
    field_key VARCHAR(100) NOT NULL,
    field_type VARCHAR(20) NOT NULL,
    content_zh TEXT,
    content_en TEXT,
    published_content_zh TEXT,
    published_content_en TEXT,
    published_at TIMESTAMP,
    max_length INT,
    is_required BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    version INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cms_content_items_page_field UNIQUE(page_id, field_key),
    CONSTRAINT fk_cms_content_items_page FOREIGN KEY (page_id) REFERENCES cms_pages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cms_content_items_page_id ON cms_content_items(page_id);
CREATE INDEX IF NOT EXISTS idx_cms_content_items_field_key ON cms_content_items(field_key);

-- ============================================
-- CMS 内容版本表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_content_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_item_id BIGINT,
    version_number INT NOT NULL,
    content_zh TEXT,
    content_en TEXT,
    changed_by BIGINT,
    change_summary VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_content_versions_item FOREIGN KEY (content_item_id) REFERENCES cms_content_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_cms_content_versions_user FOREIGN KEY (changed_by) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_content_versions_item_id ON cms_content_versions(content_item_id);
CREATE INDEX IF NOT EXISTS idx_cms_content_versions_created_at ON cms_content_versions(created_at DESC);

-- ============================================
-- CMS 资源表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_key VARCHAR(255) UNIQUE NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    large_url VARCHAR(500),
    medium_url VARCHAR(500),
    small_url VARCHAR(500),
    thumbnail_url VARCHAR(500),
    file_size BIGINT NOT NULL,
    width INT,
    height INT,
    mime_type VARCHAR(50),
    is_processed BOOLEAN DEFAULT FALSE,
    webp_converted BOOLEAN DEFAULT FALSE,
    processing_status VARCHAR(20) DEFAULT 'pending',
    alt_text_zh VARCHAR(255),
    alt_text_en VARCHAR(255),
    uploaded_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_assets_uploader FOREIGN KEY (uploaded_by) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_assets_category ON cms_assets(category);
CREATE INDEX IF NOT EXISTS idx_cms_assets_created_at ON cms_assets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cms_assets_processing_status ON cms_assets(processing_status);
CREATE INDEX IF NOT EXISTS idx_cms_assets_file_key ON cms_assets(file_key);

-- ============================================
-- CMS 资源使用表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_asset_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT,
    usage_type VARCHAR(50) NOT NULL,
    usage_id BIGINT NOT NULL,
    field_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_asset_usages_asset FOREIGN KEY (asset_id) REFERENCES cms_assets(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cms_asset_usages_asset_id ON cms_asset_usages(asset_id);
CREATE INDEX IF NOT EXISTS idx_cms_asset_usages_usage ON cms_asset_usages(usage_type, usage_id);

-- ============================================
-- CMS 路线表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_zh VARCHAR(200) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    short_desc_zh TEXT,
    short_desc_en TEXT,
    full_desc_zh TEXT,
    full_desc_en TEXT,
    distance DECIMAL(10, 2),
    difficulty VARCHAR(20),
    duration INT,
    price DECIMAL(10, 2),
    cover_image_id BIGINT,
    status VARCHAR(20) DEFAULT 'draft',
    is_featured BOOLEAN DEFAULT FALSE,
    view_count INT DEFAULT 0,
    booking_count INT DEFAULT 0,
    created_by BIGINT,
    version INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_routes_cover_image FOREIGN KEY (cover_image_id) REFERENCES cms_assets(id),
    CONSTRAINT fk_cms_routes_creator FOREIGN KEY (created_by) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_routes_status ON cms_routes(status);
CREATE INDEX IF NOT EXISTS idx_cms_routes_featured ON cms_routes(is_featured);
CREATE INDEX IF NOT EXISTS idx_cms_routes_slug ON cms_routes(slug);
CREATE INDEX IF NOT EXISTS idx_cms_routes_difficulty ON cms_routes(difficulty);

-- ============================================
-- CMS 路线图片表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_route_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT,
    asset_id BIGINT,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_route_images_route FOREIGN KEY (route_id) REFERENCES cms_routes(id) ON DELETE CASCADE,
    CONSTRAINT fk_cms_route_images_asset FOREIGN KEY (asset_id) REFERENCES cms_assets(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cms_route_images_route_id ON cms_route_images(route_id);
CREATE INDEX IF NOT EXISTS idx_cms_route_images_display_order ON cms_route_images(display_order);

-- ============================================
-- CMS 路线亮点表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_route_highlights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT,
    title_zh VARCHAR(100) NOT NULL,
    title_en VARCHAR(100) NOT NULL,
    description_zh TEXT,
    description_en TEXT,
    icon VARCHAR(50),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_route_highlights_route FOREIGN KEY (route_id) REFERENCES cms_routes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cms_route_highlights_route_id ON cms_route_highlights(route_id);

-- ============================================
-- CMS 商品表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_zh VARCHAR(200) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    short_desc_zh TEXT,
    short_desc_en TEXT,
    full_desc_zh TEXT,
    full_desc_en TEXT,
    category VARCHAR(50),
    original_price DECIMAL(10, 2),
    current_price DECIMAL(10, 2),
    stock_quantity INT DEFAULT 0,
    cover_image_id BIGINT,
    merchant_name VARCHAR(100),
    merchant_address VARCHAR(255),
    merchant_contact VARCHAR(100),
    status VARCHAR(20) DEFAULT 'draft',
    view_count INT DEFAULT 0,
    sale_count INT DEFAULT 0,
    created_by BIGINT,
    version INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_products_cover_image FOREIGN KEY (cover_image_id) REFERENCES cms_assets(id),
    CONSTRAINT fk_cms_products_creator FOREIGN KEY (created_by) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_products_status ON cms_products(status);
CREATE INDEX IF NOT EXISTS idx_cms_products_slug ON cms_products(slug);
CREATE INDEX IF NOT EXISTS idx_cms_products_category ON cms_products(category);

-- ============================================
-- CMS 商品图片表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    asset_id BIGINT,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_product_images_product FOREIGN KEY (product_id) REFERENCES cms_products(id) ON DELETE CASCADE,
    CONSTRAINT fk_cms_product_images_asset FOREIGN KEY (asset_id) REFERENCES cms_assets(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cms_product_images_product_id ON cms_product_images(product_id);

-- ============================================
-- CMS 合作伙伴表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    description_zh TEXT,
    description_en TEXT,
    logo_id BIGINT,
    website_url VARCHAR(255),
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    version INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_partners_logo FOREIGN KEY (logo_id) REFERENCES cms_assets(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_partners_type ON cms_partners(type);
CREATE INDEX IF NOT EXISTS idx_cms_partners_active ON cms_partners(is_active);
CREATE INDEX IF NOT EXISTS idx_cms_partners_display_order ON cms_partners(display_order);

-- ============================================
-- CMS 系统设置表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT,
    setting_type VARCHAR(20) DEFAULT 'string',
    description VARCHAR(255),
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_system_settings_updater FOREIGN KEY (updated_by) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_system_settings_key ON cms_system_settings(setting_key);

-- ============================================
-- CMS 操作日志表
-- ============================================
CREATE TABLE IF NOT EXISTS cms_operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50),
    resource_id BIGINT,
    details TEXT,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cms_operation_logs_user FOREIGN KEY (user_id) REFERENCES cms_admin_users(id)
);

CREATE INDEX IF NOT EXISTS idx_cms_operation_logs_user_id ON cms_operation_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_cms_operation_logs_action ON cms_operation_logs(action);
CREATE INDEX IF NOT EXISTS idx_cms_operation_logs_resource ON cms_operation_logs(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_cms_operation_logs_created_at ON cms_operation_logs(created_at DESC);
